### ISSUE TITLE
Type error: Property 'appointmentList' is missing in type

### ISSUE THREAD

**Issue by jappcare** [Jappcareauto/admin_cms_jappcare#1]
**Describe the bug**
The deployement file can't run because of a type error file in the code you pushed 

**To Reproduce**
1. Try Building the File again and display the results 
2. Failed to compile.

./app/admin/appointments/page.tsx:189:35
Type error: Property 'appointmentList' is missing in type '{ onClose: Dispatch<SetStateAction<boolean>>; }' but required in type 'AppointmentCalendarModalProps'.

  187 |             }
  188 |              {
> 189 |                 (openCalendar) ? <AppointmentCalendarModal onClose={setOpenCalendar}  /> : null
      |                                   ^
  190 |             }
  191 |         </section>
  192 |     )

**Expected behavior**
The File error is not suppose to happen its suppose to build to completion during the workflow

**Screenshots**
A Screenshot of the problem

<img width="1250" alt="Screenshot 2024-11-23 at 07 19 34" src="https://github.com/user-attachments/assets/9d23a2de-33aa-4132-afc5-c67ad39b6d6d">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jappcare** [comment]
@menosi  Please treat this as a super high issue the workflow for admin has been paused due to this please check what the issue why its behaving like that even my vscode shows that error

**Comment by Liquidator75** [comment]
@menosi  Please treat this as a super high issue the workflow for admin has been paused due to this please check what the issue why its behaving like that even my vscode shows that error

**Comment by Liquidator75** [comment]
@menosi okay thanks it has already been deployed
