### ISSUE TITLE
Correct Default Login page for dev enviroment

### ISSUE THREAD

**Issue by jappcare** [Jappcareauto/admin_cms_jappcare#5]
**Describe the bug**
We don't want to use the port to login into the admin host panel we want to use /admin can you pelase give the root directory of the default page to hsow this 

**To Reproduce**
1. Try login from the main admin url host 

**Expected behavior**
let the page display /admin
together with the service center /service-center

**Screenshots**
<img width="1280" alt="Screenshot 2024-11-27 at 20 49 11" src="https://github.com/user-attachments/assets/a3d4f359-c587-45ed-8bb5-59bb2784b861">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Liquidator75** [comment]
@menosi fixed the issue 

![Screenshot 2024-12-01 at 12 59 00](https://github.com/user-attachments/assets/7e6e1700-3f01-45b7-9719-428c5b192d8b)

**Comment by jappcare** [comment]
@SimoOdilon27 we will need to check why these logins are not going through

**Comment by Liquidator75** [comment]
fixed issue closing now
